# Generated by Django 2.1 on 2018-09-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmnet',
            options={'verbose_name': 'Associazione reti', 'verbose_name_plural': 'Associazioni reti'},
        ),
        migrations.AddField(
            model_name='testeripaddress',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Gateway'),
        ),
        migrations.AlterField(
            model_name='vmnet',
            name='ip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orchestrator.TesterIpAddress', verbose_name='Indirizzo IP'),
        ),
        migrations.AlterField(
            model_name='vmnet',
            name='net',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.Network', verbose_name='Rete'),
        ),
        migrations.AlterField(
            model_name='vmnet',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.VirtualMachine', verbose_name='VM'),
        ),
    ]
