# Generated by Django 2.1 on 2018-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_auto_20180903_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='bridge_name',
            field=models.CharField(max_length=5, unique=True, verbose_name='Nome bridge'),
        ),
    ]
