# Generated by Django 2.1 on 2018-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_auto_20180904_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='vmid',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='VM ID'),
        ),
    ]
